### ISSUE TITLE
Finalize Sensor extension schema

### ISSUE THREAD

**Issue by aufdenkampe** [UCHIC/ODM2#49]
This is our last extension schema that needs work since our addition of the FeatureAction table and highly relevant changes to the  Equipment, DataQuality and Provenance schemas.  However, let's wait until we finish our current review of Results.  Issue #42 should be considered when working on this.

**Comment by horsburgh** [comment]
This one is very old.  I believe that we have settled on the Equipment extension and how we are handling what was originally in the "Sensors" extension. If there are remaining issues they should be created separately given that "Equipment" has effectively replaced "Sensors".
