### ISSUE TITLE
Controlled Vocabularies: Create all CV entities and PK:FK relationships

### ISSUE THREAD

**Issue by aufdenkampe** [UCHIC/ODM2#5]
Assigned during **2014-1-17 ODM2 Working Teleconference**.  See notes here: https://docs.google.com/a/stroudcenter.org/document/d/1P0y-NNNiKQ170dUkHmU2XUrHku2rVB9CNhFR3YVf6R8/edit#bookmark=id.ag5ij1ga6yrs

**Comment by horsburgh** [comment]
Ha ha - funny that this was a priority in January of 2014.  This is now done.
