### ISSUE TITLE
SamplingFeatureTypeCV, SamplingFeatureGeoypeCV and SiteTypeCV discussion: scope, content, etc

### ISSUE THREAD

**Issue by emiliom** [UCHIC/ODM2#64]
This is a stub for discussions on CV's related to geospatial and environment descriptors for sampling features. Some related issues are issue #31, #16, and possibly #13. It's also helpful to [refer to the SamplingFeatures schema](http://uchic.github.io/ODM2/schemas/ODM2_Current/diagrams/ODM2SamplingFeatures.html).

**Comment by horsburgh** [comment]
I believe most of these decisions have been made.  The CVs have now been implemented at http://vocabulary.odm2.org.  This is a departure from our original plan to host everything at MMI. There may still be some discussions to be had about this stuff, but I'm going to close this issue for now.

**Comment by dr-shorthair** [comment]
You may also want to link to/recognize the OGC URIs for some of these concepts - see http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/


Simon Cox | Research Scientist
CSIRO Land and Water
PO Box 56, Highett Vic 3190, Australia
Tel +61 3 9252 6342<tel:%2B61%203%209252%206342> | Mob +61 403 302 672<tel:%2B61%20403%20302%20672>
simon.cox@csiro.au<mailto:simon.cox@csiro.au> | http://csiro.au/people/SimonCox
________________________________
