### ISSUE TITLE
ODM2CV: Implement All CVs

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#71]
Right now the ODM2 CV web application works with a subset of the CVs.  The following need to be done:

- [x] Create database tables for all of the ODM2 CVs following the pattern established for the existing ones
- [x] Import data for each CV from the Google Spreadsheet
- [x] Implement models and views for each CV in the web application

**Comment by denvaar** [comment]
Are we missing any other CV's in the database?
+----------------------------------+
| Tables_in_odmcvs                 |
+----------------------------------+
| actiontypecv                     |
| actiontypecvrequests             |
| methodtypecv                     |
| methodtypecvrequests             |
| organizationtypecv               |
| organizationtypecvrequests       |
| samplingfeaturegeotypecv         |
| samplingfeaturegeotypecvrequests |
| samplingfeaturetypecv            |
| samplingfeaturetypecvrequests    |
| sitetypecv                       |
| sitetypecvrequests               |
+----------------------------------+

**Comment by horsburgh** [comment]
Yes. There are many.  See the status Google document:  https://docs.google.com/document/d/1MbAAzwrmG--1HKJwrc9NW_hQEQcNZUlY1zjbBfdLXwA/edit#heading=h.7f0qtwilza1s

**Comment by denvaar** [comment]
This is finished with the exception of some of the database tables for requests.
