### ISSUE TITLE
ODM2CV: Modifications to Web Interface Views

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#72]
The following initial changes need to be made to the ODM2CV web user interface views:

- [x] Change all references to "ODM2 **Control** Vocabularies" to "ODM2 **Controlled** Vocabularies"
- [x] Add the description of each CV from the [status google document](https://docs.google.com/document/d/1MbAAzwrmG--1HKJwrc9NW_hQEQcNZUlY1zjbBfdLXwA/edit#heading=h.7f0qtwilza1s) to the front page and to the top of the view for the individual CV (just above the table of terms)
- [x] Add the following text to the footer of each page:

This material is based upon work supported by the National Science Foundation under Grants 1224638 and 1332257. Any opinions, fndings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation. 

- [x] Change the text on the front page to the following:

Version 2 of the Observations Data Model (ODM2) has several controlled vocabularies. This web page was developed to promote consistency between different instances of ODM2 through a community moderated system for managing the master controlled vocabularies. This web page displays the master controlled vocabulary entries and allows you to request additions or changes to these. You may then use these terms in an ODM2 database or in files that are intended to be interoperable with ODM2. 

Changes that you request are forwarded to the moderators who will attend to requests as promptly as possible. When you submit a request, you should receive an email verifying that your request has been received. When your request is approved, you should also receive an email confirmation. If you have a request that cannot be accommodated on this website, please contact the moderators:

- [x] Make sure the title link at the top of every page is linked to the home page.  Right now it links to whatever page you are on.
- [x] Provide a link at the top of each CV page to the API URL for the same content.  For example on the page http://vocabulary.odm2.org/actiontype/ add a link to http://vocabulary.odm2.org/api/v1/actiontypecv/?format=skos.  The text of the link should say "View this **CV** in SKOS" for an entire CV or "View this **term** in SKOS" for an individual term.
- [x] Modify the view for the individual term to take up the full width of the application.  Right now it only uses about half of it.
- [x] Modify the Add term form to take up the full width of the application.  Right now it takes up about half of the width.
- [ ] Make the Add term form more compact vertically.  The text boxes don't need to be quite as long vertically.  
- [x] On the page for viewing a vocabulary, make it more obvious that you can click on each of the terms to get to a page for each term.  Right now the link text is too similar to the other text.
- [x] On the page for viewing a vocabulary, implement three columns:  Term, Name, Definition
- [ ] On the Add term form, change "Submitter name" to "Your name", change "Submitter email" to "Your email", and "Request reason" to "Reason for your request"

**Comment by denvaar** [comment]
On the page for viewing a vocabulary, should the name column, or the term column provide a link to the term?

**Comment by horsburgh** [comment]
Just go with the first column (Term), but make it more obvious that it is a link.  Right now the link text looks just like all of the other text.

**Comment by horsburgh** [comment]
I'm going to close this. The vertical compactness doesn't seem like such a big deal now, and with the help text, the last item in the list should go away.
