### ISSUE TITLE
ODM2CV:  Some CV Attributes Got Truncated when Creating Database Tables

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#79]
When moving some of the data out of the Google spreadsheets, some of the values for some of the attributes got truncated because there were commas in the the attribute values.  For example, see:

- ResultTypeCV
- AggregationStatisticCV
- CensorCodeCV
- DirectiveTypeCV
- StatusCV
- AnnotationTypeCV
- ...

The list goes on.  It's long enough that the data import probably needs to be done again more most of the CV tables.

**Comment by denvaar** [comment]
Since we created the new database, these truncations have been resolved. There may be some that I have not noticed, but for now I am marking this closed.
