### ISSUE TITLE
ODM2CV: Add option to download a vocabulary as a CSV file

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#85]
In addition to being able to download an RDF/XML document, add a feature to download the CV as a comma separated values (CSV) table.

**Comment by denvaar** [comment]
Is this how the format should be?

category ,  FieldActivity
definition ,  A specialized form of an expedition action that involves an ocean-going vessel. Cruise actions are typically parents to other related Actions.
term ,  cruise
name ,  Cruise
provenance ,  
note ,  Parent to site visit actions and other actions
provenance_uri ,  
produces_result ,  No
resource_uri ,  /api/v1/actiontype/cruise/

**Comment by denvaar** [comment]
or is this better:
category,definition,term,name,provenance,note,provenance_uri,produces_result,resource_uri
FieldActivity,A specialized form of an expedition action that involves an ocean-going vessel. Cruise actions are typically parents to other related Actions.,cruise,Cruise,,Parent to site visit actions and other actions,,No,/api/v1/actiontype/cruise/

**Comment by emiliom** [comment]
My 2 cents:
- The second form is better (no spaces around the comma delimiter)
- Values should be quoted (even empty ones), b/c some of them can contain commas

**Comment by denvaar** [comment]
I've added the ability to download a CSV file on the sandbox development server, it's ready to be tested.

**Comment by horsburgh** [comment]
In the CSV file, I would like the columns to appear in this order:

Term
Name
Definition
Category
Provenance
ProvenanceURI
Note

After this should appear any custom fields for the CV (e.g., ProducesResult) for the ActionTypeCV

Last should be a column with the URI to the term.  The URI should be the full resolvable URL for the term as given in the SKOS document. For example: http://vocabulary.odm2.org/actiontype/cruise

**Comment by denvaar** [comment]
Ok, I've added this functionallity to the sandbox machine.
