### ISSUE TITLE
ODM2CV: Need help text to describe what should be entered into each field

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#88]
On the submit new term form we need help text that tells people what to put in each field.  I suggest the following:

Term:  Please enter a URI-friendly version of your term with no spaces, special characters, etc.
Name: Please enter the term as you would expect it to appear in a sentence
Definition:  Please enter a detailed definition of the term.
Category: You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.
Provenance: Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.
ProvenanceURI: If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.
Note: Please enter any additional notes you may have about the term.
Request notes: **This is an admin field and should not be exposed to regular users when submitting terms. It should appear for admins when reviewing terms.**
Submitter Name: Enter your name (could also just use example text in the field)
Submitter Email: Enter your email (could also just use example text in the field)
Request reason:  Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)

**Comment by denvaar** [comment]
Are you thinking just some static text above or below the field, or something dynamic that pops up a tool tip?

**Comment by horsburgh** [comment]
Either way. But I get annoyed by trying to find tooltip text and then how it pops up every time I hover over something.  So, I would probably vote for static text.

**Comment by denvaar** [comment]
Added some static text above each field. Also removed "Request Notes" from the form for non-admins. Changes have been pushed to production.
