### ISSUE TITLE
ODM2CV: Submitter Email should be required for all requests

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#91]
The following are the required fields for all requests:

Term
Name
Definition
SubmitterName
SubmitterEmail
RequestReason

**Comment by denvaar** [comment]
The 'New Request' form has been updated accordingly on the sandbox.

**Comment by horsburgh** [comment]
I think this looks good.  Let's push to production.

**Comment by jcaraballo17** [comment]
Shouldn't this change be made also in the database?

**Comment by horsburgh** [comment]
Whatever you need to do to implement this, yes. If it's required on the form, it should be required in the database.

**Comment by denvaar** [comment]
Pushing changes with this update and also updated the database with appropriate 'NOT NULL' restrictions.
