### ISSUE TITLE
ODM2CV: CV API only returns first 20 terms

### ISSUE THREAD

**Issue by horsburgh** [UCHIC/ODM2#96]
The script runs successfully, but I only have 20 records in my CV_VariableName table.  Testing on Windows with Microsoft SQL Server.

**Comment by miguelcleon** [comment]
I can confirm I get the same thing in PostgreSQL.

**Comment by horsburgh** [comment]
Update - I originally thought this was an issue with the CV loader script, but it is an issue with the CV API that is only returning the top 20 terms right now.  Re-assigned to Denver.

**Comment by denvaar** [comment]
I've updated the sandbox and the production servers to remove the 20 term limit.

**Comment by horsburgh** [comment]
Looks good.  Thanks.
